### PR TITLE
PP-5475 Update payment external states

### PR DESCRIPTION
**Pull request by stephencdaly**
Rename "started" to "created" and add new "paidout" and "indemnityclaim" external states.
Remove the EXTERNAL_EXPIRED and EXTERNAL_CANCELLED_USER_NOT_ELIGIBLE external states.

### CODE REVIEW

**Comment by oswaldquek** [comment]
Are the EXTERNAL_EXPIRED and EXTERNAL_CANCELLED_USER_NOT_ELIGIBLE payment states meant to be deleted too?

**Comment by stephencdaly** [comment]
Oh yeh they have been, I just didn't mention that in the commit message...

**Comment by oswaldquek** [comment]
could you explicitly mention that in the commit message? on looking at the PR it looks like EXTERNAL_EXPIRED/EXTERNAL_CANCELLED_USER_NOT_ELIGIBLE was renamed to paidout/indemnityclaim, as well as the rename from "started" to "Created"

**Comment by stephencdaly** [comment]
I've updated the commit message

**Pull request merged**
